---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksa-example
  labels:
    app: eksa-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eksa-example
  template:
    metadata:
      labels:
        app: eksa-example
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/aws-containers/hello-eks-anywhere:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eksa-example
  namespace: eksa-example
  labels:
    app: eksa-example
spec:
  type: NodePort
  selector:
    app: eksa-example
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
