apiVersion: v1
kind: Service
metadata:
  name: eks-example
  namespace: eks-example
  labels:
    app: eks-example
spec:
  selector:
    app: eks-example
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
